common: &default_settings
  license_key: "<%= Settings.newrelic_license_key %>"
  app_name: "<%= Settings.newrelic_app_name %>"
  log_level: "<%= Settings.newrelic_log_level %>"

development:
  <<: *default_settings
  app_name: "<%= Settings.newrelic_app_name %>"
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: "<%= Settings.newrelic_app_name %>"

production:
  <<: *default_settings
